In [2]:
import re
import os
import numpy as np
import pandas as pd
import shutil
import json
import matplotlib.pyplot as plt
import matplotlib.cm as cm
from sklearn.neighbors import KDTree
from tqdm import tqdm

In [3]:
# === Getting standards info ===

def get_standards(stand_path):

    #standards_path = '/home/frz603/DSP/matrix_standards/standards_positive.xlsx'
    standards_table = pd.read_excel(stand_path, skiprows=4, header = 0)

    # Reformating the info
    indices = [1, 2, 3, 6] + list(range(31, 41))
    standards = standards_table.iloc[:, indices].reset_index(drop = True)
    standards = standards[standards['Metabolite name']!='Unknown'].reset_index(drop = True)
    standards["Average Rt(min)"]=standards["Average Rt(min)"]*60
    standards["Metabolite name"] = standards["Metabolite name"].str.replace("w/o MS2:", "", regex=False).reset_index(drop=True)

    return standards

In [4]:

standards_path = '/home/frz603/DSP/matrix_standards/standards_positive.xlsx'
standards = get_standards(standards_path)
standards

,Average Rt(min),Average Mz,Metabolite name,Fill %,MS/MS spectrum,230503_Batch2_100,230503_Batch2_85,230503_Batch2_86,230503_Batch2_94,230503_Batch2_95,230503_Batch2_96,230503_Batch2_97,230503_Batch2_98,230503_Batch2_99
0,873.00,117.00352,Succinic acid,0.333,NaN,0,0,0,4916,4349,3031,0,0,0
1,966.78,117.00381,Succinic acid,0.333,NaN,0,0,0,3987,3276,2106,0,0,0
2,157.68,119.03705,Succinic acid,0.222,NaN,0,0,0,3027,2345,0,0,0,0
3,324.54,119.03815,Succinic acid,0.556,NaN,0,0,0,35034,28061,16718,8528,4771,0
4,704.64,119.05167,Succinic acid,0.444,NaN,0,0,0,13690,11208,6956,3257,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176,1174.68,633.16052,Rutin,0.111,NaN,31094,0,0,0,0,0,0,0,0
177,822.06,649.12244,RUTOSIDE (rutin),0.333,NaN,0,0,0,11812,8725,4264,0,0,0
178,715.32,649.12939,RUTOSIDE (rutin),0.667,NaN,0,0,0,478694,400218,242155,101850,34028,4032
179,1175.40,649.13556,RUTOSIDE (rutin),0.111,NaN,9232,0,0,0,0,0,0,0,0
180,58.86,707.21045,SUCROSE,0.111,NaN,0,0,0,9967,0,0,0,0,0

In [6]:
# Selecting only flavonoids from standards (Ewa says they are the most prominent)
flavonoids = ['Luteolin', 'Kaempferol', 'Kaempferol-7-neohesperidoside', 'Naringenin', 'Luteolin', 'Luteolin-6-C-glucoside', 'Rutin', 'ellagic acid', 'ellagic_acid', '(-)-Epigallocatechin-3-O-gallate', '(-)-epigallocatechin gallate', 'quercitrin', 'Quercitrin', 'Quercetin 3-O-alpha-rhamnopyranoside', 'Naringenin', 'Apigenin']

In [7]:
# Selecting one for now
stand_name = flavonoids[0]
stand_mz = np.median(np.array(standards.loc[standards['Metabolite name'] == stand_name, "Average Mz"]))
stand_rt = np.array(standards.loc[standards['Metabolite name'] == stand_name, 'Average Rt(min)'])

stand = standards[standards['Metabolite name'] == stand_name].sort_values(by = 'Average Rt(min)')
stand

,Average Rt(min),Average Mz,Metabolite name,Fill %,MS/MS spectrum,230503_Batch2_100,230503_Batch2_85,230503_Batch2_86,230503_Batch2_94,230503_Batch2_95,230503_Batch2_96,230503_Batch2_97,230503_Batch2_98,230503_Batch2_99
132,340.08,287.06134,Luteolin,0.444,NaN,0,0,0,37821,33024,17780,4350,0,0
129,558.90,287.06104,Luteolin,0.556,NaN,0,0,0,32564,24854,13499,5682,3218,0
131,682.80,287.06125,Luteolin,0.444,NaN,0,0,0,20978,14608,7300,3073,0,0
128,769.62,287.06094,Luteolin,0.333,NaN,0,0,0,9940,7229,3778,0,0,0
133,822.54,287.06186,Luteolin,0.667,NaN,0,0,0,747508,569939,298282,120448,56074,10510
134,1025.88,287.06226,Luteolin,0.778,NaN,7994,0,0,3971776,3192775,1854988,845740,415890,82678

In [8]:
path_ms_files = "/home/frz603/DSP/matrix_standards/raw_images/clustering/labels_20/sn3_w6/single_labels_overlap"

# === List all PNG files ===
all_files = [f for f in os.listdir(path_ms_files) if f.endswith(".npy")]

# === Separate into MS1 and MS2 lists ===
ms1_files = [f for f in all_files if "MS1_" in f]
ms2_files = [f for f in all_files if "MS2_" in f]

# === Print summary ===
print(f"Found {len(ms1_files)} MS1 files")
print(f"Found {len(ms2_files)} MS2 files")

Found 2833 MS1 files
Found 1447 MS2 files

In [9]:
# === Parameters ===
BINARY = False  # If True, convert to grayscale and binarize before sum

def image_projection_embedding(img_path):
    #img = Image.open(img_path).convert("L")  # grayscale
    arr = np.load(img_path)

    if BINARY:
        arr = (arr > 128).astype(int)

    row_sum = arr.sum(axis=1)  # shape (H,)
    col_sum = arr.sum(axis=0)  # shape (W,)
    vec = np.concatenate([row_sum, col_sum])

    # Normalize so max is 1
    max_val = vec.max()
    if max_val > 0:
        vec = vec / max_val

    return vec

def extract_embeddings(file_list, folder):
    embeddings = []
    valid_names = []
    for fname in tqdm(file_list):
        try:
            path = os.path.join(folder, fname)
            vec = image_projection_embedding(path)
            embeddings.append(vec)
            valid_names.append(fname)
        except Exception as e:
            print(f"Error processing {fname}: {e}")
    return np.array(embeddings), valid_names

In [10]:
ms1_vectors, ms1_names = extract_embeddings(ms1_files, path_ms_files)
ms2_vectors, ms2_names = extract_embeddings(ms2_files, path_ms_files)

ms1_names

  0%|          | 0/2833 [00:00<?, ?it/s]

100%|██████████| 2833/2833 [00:08<00:00, 330.97it/s]
100%|██████████| 1447/1447 [00:04<00:00, 294.48it/s]

['standardsnpy_MS1_130_0_130_1_004.npy',
 'standardsnpy_MS1_689_1_689_2_000.npy',
 'standardsnpy_MS1_257_2_257_3_000.npy',
 'standardsnpy_MS1_429_0_429_1_001.npy',
 'standardsnpy_MS1_634_0_634_1_001.npy',
 'standardsnpy_MS1_134_9_135_0_004.npy',
 'standardsnpy_MS1_487_0_487_1_002.npy',
 'standardsnpy_MS1_181_1_181_2_000.npy',
 'standardsnpy_MS1_130_0_130_1_003.npy',
 'standardsnpy_MS1_612_0_612_1_001.npy',
 'standardsnpy_MS1_191_0_191_1_000.npy',
 'standardsnpy_MS1_758_1_758_2_000.npy',
 'standardsnpy_MS1_379_1_379_2_001.npy',
 'standardsnpy_MS1_287_3_287_4_001.npy',
 'standardsnpy_MS1_279_0_279_1_036.npy',
 'standardsnpy_MS1_213_0_213_1_002.npy',
 'standardsnpy_MS1_201_9_202_0_000.npy',
 'standardsnpy_MS1_303_1_303_2_003.npy',
 'standardsnpy_MS1_485_2_485_3_000.npy',
 'standardsnpy_MS1_627_0_627_1_002.npy',
 'standardsnpy_MS1_384_2_384_3_000.npy',
 'standardsnpy_MS1_132_0_132_1_003.npy',
 'standardsnpy_MS1_729_2_729_3_000.npy',
 'standardsnpy_MS1_165_0_165_1_000.npy',
 'standardsnpy_MS1_319_1_319_2_004.npy',
 'standardsnpy_MS1_359_1_359_2_006.npy',
 'standardsnpy_MS1_245_0_245_1_002.npy',
 'standardsnpy_MS1_208_0_208_1_000.npy',
 'standardsnpy_MS1_550_2_550_3_000.npy',
 'standardsnpy_MS1_229_1_229_2_002.npy',
 'standardsnpy_MS1_617_1_617_2_000.npy',
 'standardsnpy_MS1_192_9_193_0_001.npy',
 'standardsnpy_MS1_474_1_474_2_000.npy',
 'standardsnpy_MS1_391_1_391_2_001.npy',
 'standardsnpy_MS1_401_1_401_2_000.npy',
 'standardsnpy_MS1_209_9_210_0_000.npy',
 'standardsnpy_MS1_416_2_416_3_000.npy',
 'standardsnpy_MS1_368_0_368_1_001.npy',
 'standardsnpy_MS1_161_0_161_1_002.npy',
 'standardsnpy_MS1_266_0_266_1_000.npy',
 'standardsnpy_MS1_259_0_259_1_005.npy',
 'standardsnpy_MS1_170_1_170_2_000.npy',
 'standardsnpy_MS1_173_0_173_1_003.npy',
 'standardsnpy_MS1_980_0_980_1_000.npy',
 'standardsnpy_MS1_370_0_370_1_000.npy',
 'standardsnpy_MS1_194_1_194_2_000.npy',
 'standardsnpy_MS1_225_9_226_0_000.npy',
 'standardsnpy_MS1_504_0_504_1_000.npy',
 'standardsnpy_MS1_219_2_219_3_000.npy',
 'standardsnpy_MS1_344_9_345_0_002.npy',
 'standardsnpy_MS1_551_2_551_3_000.npy',
 'standardsnpy_MS1_335_0_335_1_000.npy',
 'standardsnpy_MS1_392_1_392_2_000.npy',
 'standardsnpy_MS1_115_0_115_1_000.npy',
 'standardsnpy_MS1_287_0_287_1_000.npy',
 'standardsnpy_MS1_975_1_975_2_000.npy',
 'standardsnpy_MS1_279_0_279_1_047.npy',
 'standardsnpy_MS1_279_0_279_1_000.npy',
 'standardsnpy_MS1_159_1_159_2_002.npy',
 'standardsnpy_MS1_233_0_233_1_001.npy',
 'standardsnpy_MS1_237_1_237_2_000.npy',
 'standardsnpy_MS1_626_0_626_1_001.npy',
 'standardsnpy_MS1_205_1_205_2_000.npy',
 'standardsnpy_MS1_235_0_235_1_000.npy',
 'standardsnpy_MS1_405_2_405_3_000.npy',
 'standardsnpy_MS1_346_9_347_0_000.npy',
 'standardsnpy_MS1_206_9_207_0_000.npy',
 'standardsnpy_MS1_431_2_431_3_001.npy',
 'standardsnpy_MS1_371_9_372_0_000.npy',
 'standardsnpy_MS1_328_3_328_4_000.npy',
 'standardsnpy_MS1_468_0_468_1_000.npy',
 'standardsnpy_MS1_343_1_343_2_001.npy',
 'standardsnpy_MS1_516_1_516_2_000.npy',
 'standardsnpy_MS1_265_0_265_1_000.npy',
 'standardsnpy_MS1_512_2_512_3_000.npy',
 'standardsnpy_MS1_331_1_331_2_001.npy',
 'standardsnpy_MS1_475_3_475_4_001.npy',
 'standardsnpy_MS1_165_9_166_0_002.npy',
 'standardsnpy_MS1_276_0_276_1_001.npy',
 'standardsnpy_MS1_496_2_496_3_000.npy',
 'standardsnpy_MS1_208_1_208_2_000.npy',
 'standardsnpy_MS1_199_0_199_1_000.npy',
 'standardsnpy_MS1_462_1_462_2_000.npy',
 'standardsnpy_MS1_239_1_239_2_001.npy',
 'standardsnpy_MS1_139_0_139_1_000.npy',
 'standardsnpy_MS1_193_0_193_1_003.npy',
 'standardsnpy_MS1_219_0_219_1_001.npy',
 'standardsnpy_MS1_218_9_219_0_000.npy',
 'standardsnpy_MS1_365_1_365_2_023.npy',
 'standardsnpy_MS1_357_9_358_0_000.npy',
 'standardsnpy_MS1_265_1_265_2_001.npy',
 'standardsnpy_MS1_631_0_631_1_000.npy',
 'standardsnpy_MS1_171_0_171_1_002.npy',
 'standardsnpy_MS1_214_0_214_1_001.npy',
 'standardsnpy_MS1_417_0_417_1_000.npy',
 'standardsnpy_MS1_639_2_639_3_000.npy',
 'standardsnpy_MS1_146_1_146_2_000.npy',
 'standardsnpy_MS1_188_0_188_1_004.npy',
 'standardsnpy_MS1_291_2_291_3_000.npy',
 'standardsnpy_MS1_285_2_285_3_000.npy',
 'standardsnpy_MS1_379_2_379_3_005.npy',
 'standardsnpy_MS1_197_1_197_2_002.npy',
 'standardsnpy_MS1_163_0_163_1_001.npy',
 'standardsnpy_MS1_219_0_219_1_002.npy',
 'standardsnpy_MS1_158_0_158_1_001.npy',
 'standardsnpy_MS1_331_0_331_1_002.npy',
 'standardsnpy_MS1_352_0_352_1_001.npy',
 'standardsnpy_MS1_664_9_665_0_000.npy',
 'standardsnpy_MS1_183_0_183_1_000.npy',
 'standardsnpy_MS1_272_1_272_2_000.npy',
 'standardsnpy_MS1_307_9_308_0_001.npy',
 'standardsnpy_MS1_231_0_231_1_003.npy',
 'standardsnpy_MS1_310_0_310_1_000.npy',
 'standardsnpy_MS1_439_1_439_2_000.npy',
 'standardsnpy_MS1_179_0_179_1_002.npy',
 'standardsnpy_MS1_347_0_347_1_001.npy',
 'standardsnpy_MS1_272_0_272_1_000.npy',
 'standardsnpy_MS1_153_0_153_1_002.npy',
 'standardsnpy_MS1_207_0_207_1_000.npy',
 'standardsnpy_MS1_235_1_235_2_000.npy',
 'standardsnpy_MS1_426_0_426_1_001.npy',
 'standardsnpy_MS1_588_2_588_3_000.npy',
 'standardsnpy_MS1_215_0_215_1_000.npy',
 'standardsnpy_MS1_344_0_344_1_004.npy',
 'standardsnpy_MS1_198_1_198_2_000.npy',
 'standardsnpy_MS1_377_1_377_2_003.npy',
 'standardsnpy_MS1_587_2_587_3_000.npy',
 'standardsnpy_MS1_237_9_238_0_000.npy',
 'standardsnpy_MS1_425_0_425_1_000.npy',
 'standardsnpy_MS1_515_1_515_2_000.npy',
 'standardsnpy_MS1_199_0_199_1_002.npy',
 'standardsnpy_MS1_622_0_622_1_000.npy',
 'standardsnpy_MS1_367_9_368_0_001.npy',
 'standardsnpy_MS1_173_0_173_1_002.npy',
 'standardsnpy_MS1_952_0_952_1_000.npy',
 'standardsnpy_MS1_472_7_472_8_000.npy',
 'standardsnpy_MS1_164_9_165_0_002.npy',
 'standardsnpy_MS1_244_0_244_1_000.npy',
 'standardsnpy_MS1_179_0_179_1_000.npy',
 'standardsnpy_MS1_292_0_292_1_000.npy',
 'standardsnpy_MS1_329_0_329_1_002.npy',
 'standardsnpy_MS1_420_2_420_3_000.npy',
 'standardsnpy_MS1_623_0_623_1_000.npy',
 'standardsnpy_MS1_275_1_275_2_002.npy',
 'standardsnpy_MS1_254_2_254_3_000.npy',
 'standardsnpy_MS1_472_1_472_2_000.npy',
 'standardsnpy_MS1_363_2_363_3_000.npy',
 'standardsnpy_MS1_453_3_453_4_000.npy',
 'standardsnpy_MS1_395_2_395_3_000.npy',
 'standardsnpy_MS1_202_0_202_1_001.npy',
 'standardsnpy_MS1_382_0_382_1_000.npy',
 'standardsnpy_MS1_494_0_494_1_000.npy',
 'standardsnpy_MS1_257_0_257_1_002.npy',
 'standardsnpy_MS1_190_9_191_0_002.npy',
 'standardsnpy_MS1_430_1_430_2_001.npy',
 'standardsnpy_MS1_423_2_423_3_002.npy',
 'standardsnpy_MS1_133_0_133_1_001.npy',
 'standardsnpy_MS1_480_0_480_1_000.npy',
 'standardsnpy_MS1_144_0_144_1_002.npy',
 'standardsnpy_MS1_425_2_425_3_000.npy',
 'standardsnpy_MS1_716_1_716_2_000.npy',
 'standardsnpy_MS1_706_0_706_1_000.npy',
 'standardsnpy_MS1_324_9_325_0_000.npy',
 'standardsnpy_MS1_605_1_605_2_000.npy',
 'standardsnpy_MS1_597_0_597_1_000.npy',
 'standardsnpy_MS1_151_1_151_2_000.npy',
 'standardsnpy_MS1_193_0_193_1_001.npy',
 'standardsnpy_MS1_169_0_169_1_001.npy',
 'standardsnpy_MS1_134_1_134_2_000.npy',
 'standardsnpy_MS1_481_9_482_0_000.npy',
 'standardsnpy_MS1_439_2_439_3_000.npy',
 'standardsnpy_MS1_763_1_763_2_000.npy',
 'standardsnpy_MS1_643_0_643_1_000.npy',
 'standardsnpy_MS1_200_0_200_1_001.npy',
 'standardsnpy_MS1_181_0_181_1_004.npy',
 'standardsnpy_MS1_313_1_313_2_002.npy',
 'standardsnpy_MS1_578_2_578_3_000.npy',
 'standardsnpy_MS1_363_1_363_2_001.npy',
 'standardsnpy_MS1_409_1_409_2_000.npy',
 'standardsnpy_MS1_381_1_381_2_000.npy',
 'standardsnpy_MS1_497_2_497_3_000.npy',
 'standardsnpy_MS1_180_9_181_0_000.npy',
 'standardsnpy_MS1_130_0_130_1_002.npy',
 'standardsnpy_MS1_429_0_429_1_002.npy',
 'standardsnpy_MS1_383_0_383_1_002.npy',
 'standardsnpy_MS1_229_0_229_1_002.npy',
 'standardsnpy_MS1_341_1_341_2_001.npy',
 'standardsnpy_MS1_290_0_290_1_006.npy',
 'standardsnpy_MS1_287_0_287_1_001.npy',
 'standardsnpy_MS1_275_2_275_3_000.npy',
 'standardsnpy_MS1_337_2_337_3_000.npy',
 'standardsnpy_MS1_534_9_535_0_000.npy',
 'standardsnpy_MS1_511_2_511_3_001.npy',
 'standardsnpy_MS1_526_3_526_4_000.npy',
 'standardsnpy_MS1_335_1_335_2_002.npy',
 'standardsnpy_MS1_400_0_400_1_001.npy',
 'standardsnpy_MS1_217_1_217_2_001.npy',
 'standardsnpy_MS1_497_0_497_1_000.npy',
 'standardsnpy_MS1_306_0_306_1_000.npy',
 'standardsnpy_MS1_131_0_131_1_001.npy',
 'standardsnpy_MS1_365_1_365_2_001.npy',
 'standardsnpy_MS1_261_1_261_2_010.npy',
 'standardsnpy_MS1_361_0_361_1_002.npy',
 'standardsnpy_MS1_429_1_429_2_001.npy',
 'standardsnpy_MS1_149_0_149_1_000.npy',
 'standardsnpy_MS1_471_1_471_2_002.npy',
 'standardsnpy_MS1_420_0_420_1_000.npy',
 'standardsnpy_MS1_633_1_633_2_000.npy',
 'standardsnpy_MS1_496_0_496_1_001.npy',
 'standardsnpy_MS1_214_2_214_3_000.npy',
 'standardsnpy_MS1_731_4_731_5_000.npy',
 'standardsnpy_MS1_433_0_433_1_000.npy',
 'standardsnpy_MS1_365_0_365_1_002.npy',
 'standardsnpy_MS1_917_1_917_2_000.npy',
 'standardsnpy_MS1_257_1_257_2_003.npy',
 'standardsnpy_MS1_659_0_659_1_001.npy',
 'standardsnpy_MS1_500_0_500_1_000.npy',
 'standardsnpy_MS1_431_2_431_3_000.npy',
 'standardsnpy_MS1_168_9_169_0_001.npy',
 'standardsnpy_MS1_356_9_357_0_002.npy',
 'standardsnpy_MS1_542_2_542_3_001.npy',
 'standardsnpy_MS1_238_1_238_2_000.npy',
 'standardsnpy_MS1_325_1_325_2_003.npy',
 'standardsnpy_MS1_387_0_387_1_000.npy',
 'standardsnpy_MS1_262_0_262_1_003.npy',
 'standardsnpy_MS1_279_0_279_1_020.npy',
 'standardsnpy_MS1_276_0_276_1_002.npy',
 'standardsnpy_MS1_487_0_487_1_000.npy',
 'standardsnpy_MS1_579_0_579_1_000.npy',
 'standardsnpy_MS1_208_0_208_1_002.npy',
 'standardsnpy_MS1_196_1_196_2_000.npy',
 'standardsnpy_MS1_145_0_145_1_006.npy',
 'standardsnpy_MS1_198_0_198_1_002.npy',
 'standardsnpy_MS1_193_1_193_2_002.npy',
 'standardsnpy_MS1_234_1_234_2_001.npy',
 'standardsnpy_MS1_442_0_442_1_004.npy',
 'standardsnpy_MS1_212_0_212_1_000.npy',
 'standardsnpy_MS1_321_2_321_3_000.npy',
 'standardsnpy_MS1_291_1_291_2_001.npy',
 'standardsnpy_MS1_529_1_529_2_001.npy',
 'standardsnpy_MS1_406_0_406_1_000.npy',
 'standardsnpy_MS1_279_1_279_2_007.npy',
 'standardsnpy_MS1_585_2_585_3_001.npy',
 'standardsnpy_MS1_157_0_157_1_001.npy',
 'standardsnpy_MS1_250_0_250_1_003.npy',
 'standardsnpy_MS1_457_0_457_1_000.npy',
 'standardsnpy_MS1_193_1_193_2_000.npy',
 'standardsnpy_MS1_434_0_434_1_000.npy',
 'standardsnpy_MS1_204_1_204_2_001.npy',
 'standardsnpy_MS1_884_2_884_3_000.npy',
 'standardsnpy_MS1_343_9_344_0_001.npy',
 'standardsnpy_MS1_370_1_370_2_001.npy',
 'standardsnpy_MS1_279_0_279_1_010.npy',
 'standardsnpy_MS1_242_2_242_3_000.npy',
 'standardsnpy_MS1_375_9_376_0_000.npy',
 'standardsnpy_MS1_220_9_221_0_000.npy',
 'standardsnpy_MS1_407_1_407_2_001.npy',
 'standardsnpy_MS1_391_0_391_1_001.npy',
 'standardsnpy_MS1_262_0_262_1_005.npy',
 'standardsnpy_MS1_374_9_375_0_000.npy',
 'standardsnpy_MS1_304_1_304_2_000.npy',
 'standardsnpy_MS1_530_1_530_2_000.npy',
 'standardsnpy_MS1_134_9_135_0_003.npy',
 'standardsnpy_MS1_400_0_400_1_000.npy',
 'standardsnpy_MS1_89_0_89_1_000.npy',
 'standardsnpy_MS1_210_1_210_2_001.npy',
 'standardsnpy_MS1_329_0_329_1_001.npy',
 'standardsnpy_MS1_257_1_257_2_004.npy',
 'standardsnpy_MS1_165_9_166_0_000.npy',
 'standardsnpy_MS1_383_0_383_1_000.npy',
 'standardsnpy_MS1_387_1_387_2_001.npy',
 'standardsnpy_MS1_309_0_309_1_001.npy',
 'standardsnpy_MS1_670_0_670_1_000.npy',
 'standardsnpy_MS1_202_1_202_2_000.npy',
 'standardsnpy_MS1_369_1_369_2_000.npy',
 'standardsnpy_MS1_456_0_456_1_001.npy',
 'standardsnpy_MS1_351_1_351_2_000.npy',
 'standardsnpy_MS1_341_9_342_0_002.npy',
 'standardsnpy_MS1_420_1_420_2_001.npy',
 'standardsnpy_MS1_239_9_240_0_000.npy',
 'standardsnpy_MS1_907_2_907_3_000.npy',
 'standardsnpy_MS1_486_1_486_2_000.npy',
 'standardsnpy_MS1_287_4_287_5_000.npy',
 'standardsnpy_MS1_453_0_453_1_002.npy',
 'standardsnpy_MS1_160_1_160_2_000.npy',
 'standardsnpy_MS1_424_0_424_1_000.npy',
 'standardsnpy_MS1_632_1_632_2_001.npy',
 'standardsnpy_MS1_162_9_163_0_002.npy',
 'standardsnpy_MS1_345_0_345_1_000.npy',
 'standardsnpy_MS1_91_0_91_1_002.npy',
 'standardsnpy_MS1_372_0_372_1_000.npy',
 'standardsnpy_MS1_341_0_341_1_002.npy',
 'standardsnpy_MS1_285_0_285_1_001.npy',
 'standardsnpy_MS1_216_0_216_1_001.npy',
 'standardsnpy_MS1_243_0_243_1_002.npy',
 'standardsnpy_MS1_345_1_345_2_000.npy',
 'standardsnpy_MS1_262_0_262_1_006.npy',
 'standardsnpy_MS1_141_0_141_1_000.npy',
 'standardsnpy_MS1_342_0_342_1_000.npy',
 'standardsnpy_MS1_197_0_197_1_002.npy',
 'standardsnpy_MS1_973_1_973_2_000.npy',
 'standardsnpy_MS1_512_2_512_3_001.npy',
 'standardsnpy_MS1_660_0_660_1_000.npy',
 'standardsnpy_MS1_361_0_361_1_000.npy',
 'standardsnpy_MS1_366_0_366_1_000.npy',
 'standardsnpy_MS1_449_1_449_2_001.npy',
 'standardsnpy_MS1_935_1_935_2_001.npy',
 'standardsnpy_MS1_180_9_181_0_001.npy',
 'standardsnpy_MS1_525_0_525_1_000.npy',
 'standardsnpy_MS1_169_1_169_2_002.npy',
 'standardsnpy_MS1_571_2_571_3_000.npy',
 'standardsnpy_MS1_303_1_303_2_008.npy',
 'standardsnpy_MS1_644_0_644_1_000.npy',
 'standardsnpy_MS1_399_0_399_1_001.npy',
 'standardsnpy_MS1_667_0_667_1_000.npy',
 'standardsnpy_MS1_354_9_355_0_000.npy',
 'standardsnpy_MS1_191_9_192_0_002.npy',
 'standardsnpy_MS1_353_1_353_2_003.npy',
 'standardsnpy_MS1_379_1_379_2_000.npy',
 'standardsnpy_MS1_370_1_370_2_000.npy',
 'standardsnpy_MS1_407_1_407_2_003.npy',
 'standardsnpy_MS1_301_0_301_1_002.npy',
 'standardsnpy_MS1_525_2_525_3_002.npy',
 'standardsnpy_MS1_153_0_153_1_006.npy',
 'standardsnpy_MS1_274_2_274_3_000.npy',
 'standardsnpy_MS1_387_1_387_2_004.npy',
 'standardsnpy_MS1_141_0_141_1_006.npy',
 'standardsnpy_MS1_275_0_275_1_000.npy',
 'standardsnpy_MS1_169_0_169_1_002.npy',
 'standardsnpy_MS1_132_0_132_1_001.npy',
 'standardsnpy_MS1_890_3_890_4_000.npy',
 'standardsnpy_MS1_300_0_300_1_000.npy',
 'standardsnpy_MS1_365_0_365_1_001.npy',
 'standardsnpy_MS1_278_1_278_2_000.npy',
 'standardsnpy_MS1_663_9_664_0_000.npy',
 'standardsnpy_MS1_381_0_381_1_000.npy',
 'standardsnpy_MS1_243_2_243_3_000.npy',
 'standardsnpy_MS1_403_1_403_2_001.npy',
 'standardsnpy_MS1_210_1_210_2_000.npy',
 'standardsnpy_MS1_204_9_205_0_000.npy',
 'standardsnpy_MS1_279_0_279_1_037.npy',
 'standardsnpy_MS1_241_9_242_0_000.npy',
 'standardsnpy_MS1_495_0_495_1_002.npy',
 'standardsnpy_MS1_129_0_129_1_003.npy',
 'standardsnpy_MS1_188_1_188_2_002.npy',
 'standardsnpy_MS1_279_0_279_1_001.npy',
 'standardsnpy_MS1_363_0_363_1_002.npy',
 'standardsnpy_MS1_681_1_681_2_000.npy',
 'standardsnpy_MS1_272_0_272_1_003.npy',
 'standardsnpy_MS1_442_0_442_1_001.npy',
 'standardsnpy_MS1_246_2_246_3_000.npy',
 'standardsnpy_MS1_552_1_552_2_000.npy',
 'standardsnpy_MS1_470_1_470_2_000.npy',
 'standardsnpy_MS1_321_1_321_2_000.npy',
 'standardsnpy_MS1_279_0_279_1_016.npy',
 'standardsnpy_MS1_226_0_226_1_001.npy',
 'standardsnpy_MS1_448_0_448_1_000.npy',
 'standardsnpy_MS1_305_0_305_1_001.npy',
 'standardsnpy_MS1_949_1_949_2_000.npy',
 'standardsnpy_MS1_431_1_431_2_001.npy',
 'standardsnpy_MS1_292_1_292_2_002.npy',
 'standardsnpy_MS1_260_0_260_1_000.npy',
 'standardsnpy_MS1_203_1_203_2_000.npy',
 'standardsnpy_MS1_368_0_368_1_000.npy',
 'standardsnpy_MS1_217_0_217_1_002.npy',
 'standardsnpy_MS1_185_0_185_1_004.npy',
 'standardsnpy_MS1_534_2_534_3_000.npy',
 'standardsnpy_MS1_428_2_428_3_000.npy',
 'standardsnpy_MS1_466_0_466_1_000.npy',
 'standardsnpy_MS1_130_9_131_0_000.npy',
 'standardsnpy_MS1_291_1_291_2_004.npy',
 'standardsnpy_MS1_894_2_894_3_000.npy',
 'standardsnpy_MS1_216_9_217_0_000.npy',
 'standardsnpy_MS1_358_1_358_2_000.npy',
 'standardsnpy_MS1_500_1_500_2_000.npy',
 'standardsnpy_MS1_273_0_273_1_001.npy',
 'standardsnpy_MS1_527_2_527_3_000.npy',
 'standardsnpy_MS1_948_1_948_2_000.npy',
 'standardsnpy_MS1_269_1_269_2_001.npy',
 'standardsnpy_MS1_423_1_423_2_001.npy',
 'standardsnpy_MS1_320_0_320_1_000.npy',
 'standardsnpy_MS1_363_0_363_1_001.npy',
 'standardsnpy_MS1_177_9_178_0_000.npy',
 'standardsnpy_MS1_506_1_506_2_001.npy',
 'standardsnpy_MS1_145_0_145_1_005.npy',
 'standardsnpy_MS1_357_0_357_1_004.npy',
 'standardsnpy_MS1_746_1_746_2_001.npy',
 'standardsnpy_MS1_365_2_365_3_001.npy',
 'standardsnpy_MS1_261_0_261_1_002.npy',
 'standardsnpy_MS1_451_0_451_1_001.npy',
 'standardsnpy_MS1_295_0_295_1_001.npy',
 'standardsnpy_MS1_503_0_503_1_001.npy',
 'standardsnpy_MS1_743_1_743_2_000.npy',
 'standardsnpy_MS1_174_0_174_1_005.npy',
 'standardsnpy_MS1_567_1_567_2_001.npy',
 'standardsnpy_MS1_154_0_154_1_000.npy',
 'standardsnpy_MS1_365_1_365_2_000.npy',
 'standardsnpy_MS1_504_1_504_2_001.npy',
 'standardsnpy_MS1_339_1_339_2_000.npy',
 'standardsnpy_MS1_145_0_145_1_002.npy',
 'standardsnpy_MS1_347_1_347_2_000.npy',
 'standardsnpy_MS1_445_0_445_1_000.npy',
 'standardsnpy_MS1_377_2_377_3_000.npy',
 'standardsnpy_MS1_327_0_327_1_001.npy',
 'standardsnpy_MS1_323_0_323_1_004.npy',
 'standardsnpy_MS1_132_9_133_0_000.npy',
 'standardsnpy_MS1_470_1_470_2_002.npy',
 'standardsnpy_MS1_514_2_514_3_001.npy',
 'standardsnpy_MS1_391_1_391_2_003.npy',
 'standardsnpy_MS1_355_9_356_0_000.npy',
 'standardsnpy_MS1_187_9_188_0_000.npy',
 'standardsnpy_MS1_527_2_527_3_001.npy',
 'standardsnpy_MS1_130_0_130_1_005.npy',
 'standardsnpy_MS1_123_0_123_1_000.npy',
 'standardsnpy_MS1_177_0_177_1_003.npy',
 'standardsnpy_MS1_359_9_360_0_001.npy',
 'standardsnpy_MS1_373_9_374_0_002.npy',
 'standardsnpy_MS1_500_2_500_3_000.npy',
 'standardsnpy_MS1_132_9_133_0_003.npy',
 'standardsnpy_MS1_302_0_302_1_001.npy',
 'standardsnpy_MS1_569_1_569_2_001.npy',
 'standardsnpy_MS1_427_1_427_2_000.npy',
 'standardsnpy_MS1_188_0_188_1_005.npy',
 'standardsnpy_MS1_387_1_387_2_003.npy',
 'standardsnpy_MS1_241_0_241_1_001.npy',
 'standardsnpy_MS1_427_2_427_3_002.npy',
 'standardsnpy_MS1_273_1_273_2_004.npy',
 'standardsnpy_MS1_230_0_230_1_000.npy',
 'standardsnpy_MS1_955_1_955_2_000.npy',
 'standardsnpy_MS1_427_0_427_1_000.npy',
 'standardsnpy_MS1_155_0_155_1_000.npy',
 'standardsnpy_MS1_354_1_354_2_000.npy',
 'standardsnpy_MS1_279_0_279_1_043.npy',
 'standardsnpy_MS1_134_9_135_0_002.npy',
 'standardsnpy_MS1_224_1_224_2_000.npy',
 'standardsnpy_MS1_175_0_175_1_001.npy',
 'standardsnpy_MS1_224_9_225_0_000.npy',
 'standardsnpy_MS1_357_9_358_0_002.npy',
 'standardsnpy_MS1_214_0_214_1_004.npy',
 'standardsnpy_MS1_440_0_440_1_000.npy',
 'standardsnpy_MS1_192_0_192_1_001.npy',
 'standardsnpy_MS1_145_0_145_1_004.npy',
 'standardsnpy_MS1_406_0_406_1_001.npy',
 'standardsnpy_MS1_571_3_571_4_000.npy',
 'standardsnpy_MS1_497_2_497_3_001.npy',
 'standardsnpy_MS1_307_1_307_2_005.npy',
 'standardsnpy_MS1_340_1_340_2_000.npy',
 'standardsnpy_MS1_660_0_660_1_001.npy',
 'standardsnpy_MS1_285_1_285_2_001.npy',
 'standardsnpy_MS1_205_0_205_1_003.npy',
 'standardsnpy_MS1_600_3_600_4_000.npy',
 'standardsnpy_MS1_284_9_285_0_000.npy',
 'standardsnpy_MS1_427_2_427_3_000.npy',
 'standardsnpy_MS1_127_0_127_1_001.npy',
 'standardsnpy_MS1_142_0_142_1_001.npy',
 'standardsnpy_MS1_551_1_551_2_000.npy',
 'standardsnpy_MS1_287_2_287_3_000.npy',
 'standardsnpy_MS1_444_2_444_3_000.npy',
 'standardsnpy_MS1_569_2_569_3_000.npy',
 'standardsnpy_MS1_305_1_305_2_005.npy',
 'standardsnpy_MS1_747_1_747_2_001.npy',
 'standardsnpy_MS1_389_0_389_1_001.npy',
 'standardsnpy_MS1_342_9_343_0_001.npy',
 'standardsnpy_MS1_206_0_206_1_002.npy',
 'standardsnpy_MS1_288_0_288_1_000.npy',
 'standardsnpy_MS1_279_0_279_1_021.npy',
 'standardsnpy_MS1_450_2_450_3_000.npy',
 'standardsnpy_MS1_503_2_503_3_000.npy',
 'standardsnpy_MS1_611_3_611_4_000.npy',
 'standardsnpy_MS1_374_1_374_2_000.npy',
 'standardsnpy_MS1_121_0_121_1_003.npy',
 'standardsnpy_MS1_170_9_171_0_000.npy',
 'standardsnpy_MS1_329_9_330_0_000.npy',
 'standardsnpy_MS1_308_1_308_2_000.npy',
 'standardsnpy_MS1_359_0_359_1_000.npy',
 'standardsnpy_MS1_179_0_179_1_009.npy',
 'standardsnpy_MS1_553_2_553_3_001.npy',
 'standardsnpy_MS1_314_0_314_1_000.npy',
 'standardsnpy_MS1_332_1_332_2_000.npy',
 'standardsnpy_MS1_292_1_292_2_004.npy',
 'standardsnpy_MS1_193_1_193_2_001.npy',
 'standardsnpy_MS1_183_1_183_2_000.npy',
 'standardsnpy_MS1_257_1_257_2_002.npy',
 'standardsnpy_MS1_280_1_280_2_000.npy',
 'standardsnpy_MS1_625_0_625_1_001.npy',
 'standardsnpy_MS1_378_1_378_2_000.npy',
 'standardsnpy_MS1_259_0_259_1_003.npy',

In [11]:
# === Setting parameters ===
K = 5
output_folder = f'/home/frz603/DSP/matrix_standards/raw_images/clustering/kdtree/sn3_w6_k{K}'

# === Nearest neighbor search ===
tree = KDTree(ms1_vectors)
dists, indices = tree.query(ms2_vectors, k=K, sort_results=True)

matches = pd.DataFrame([
    (ms2_names[i], ms1_names[indices[i][j]], dists[i][j])
    for i in range(len(ms2_names))
    for j in range(K)
], columns=["ms2_name", "ms1_name", "distance"])

matches.to_excel(os.path.join(output_folder, 'final_matches.xlsx'))
matches

,ms2_name,ms1_name,distance
0,standardsnpy_MS2_549_2_549_3_000.npy,standardsnpy_MS1_890_3_890_4_000.npy,0.883451
1,standardsnpy_MS2_549_2_549_3_000.npy,standardsnpy_MS1_892_3_892_4_000.npy,0.884383
2,standardsnpy_MS2_549_2_549_3_000.npy,standardsnpy_MS1_891_3_891_4_000.npy,0.885402
3,standardsnpy_MS2_549_2_549_3_000.npy,standardsnpy_MS1_906_2_906_3_000.npy,0.891328
4,standardsnpy_MS2_549_2_549_3_000.npy,standardsnpy_MS1_907_2_907_3_001.npy,0.902144
...,...,...,...
7230,standardsnpy_MS2_204_0_204_1_005.npy,standardsnpy_MS1_247_0_247_1_006.npy,0.367357
7231,standardsnpy_MS2_204_0_204_1_005.npy,standardsnpy_MS1_324_1_324_2_003.npy,0.426026
7232,standardsnpy_MS2_204_0_204_1_005.npy,standardsnpy_MS1_292_1_292_2_004.npy,0.426360
7233,standardsnpy_MS2_204_0_204_1_005.npy,standardsnpy_MS1_273_1_273_2_005.npy,0.453190
7234,standardsnpy_MS2_204_0_204_1_005.npy,standardsnpy_MS1_303_1_303_2_007.npy,0.465684

In [28]:
# === Selecting all MS1 labels in the mass slice that matches the standards ===
image_name = np.unique([f for f in ms1_names if float(f.split('_')[2]+'.'+f.split('_')[3])<=stand_mz and float(f.split('_')[4]+'.'+re.sub('.npy', '',f.split('_')[5]))>=stand_mz])
print(image_name)

['standardsnpy_MS1_287_0_287_1_000.npy'
 'standardsnpy_MS1_287_0_287_1_001.npy'
 'standardsnpy_MS1_287_0_287_1_002.npy'
 'standardsnpy_MS1_287_0_287_1_003.npy'
 'standardsnpy_MS1_287_0_287_1_004.npy'
 'standardsnpy_MS1_287_0_287_1_005.npy'
 'standardsnpy_MS1_287_0_287_1_006.npy'
 'standardsnpy_MS1_287_0_287_1_007.npy']

In [29]:
# === Getting all MS2 labels that match all selected MS1 labels ===
#spectra = matches[matches['ms1_name'].str.removesuffix(".npy").str.replace("standardsnpy_", "", regex=False).isin(image_name)].iloc[:, 1:4].reset_index(drop = True)
spectra = matches[matches['ms1_name'].isin(image_name)].sort_values(by="ms2_name").reset_index(drop = True)
spectra

,ms2_name,ms1_name,distance
0,standardsnpy_MS2_121_0_121_1_000.npy,standardsnpy_MS1_287_0_287_1_001.npy,0.078806
1,standardsnpy_MS2_121_0_121_1_002.npy,standardsnpy_MS1_287_0_287_1_004.npy,0.090316
2,standardsnpy_MS2_121_0_121_1_004.npy,standardsnpy_MS1_287_0_287_1_007.npy,0.172330
3,standardsnpy_MS2_123_0_123_1_001.npy,standardsnpy_MS1_287_0_287_1_001.npy,0.089319
4,standardsnpy_MS2_127_0_127_1_005.npy,standardsnpy_MS1_287_0_287_1_007.npy,0.200730
...,...,...,...
77,standardsnpy_MS2_665_9_666_0_000.npy,standardsnpy_MS1_287_0_287_1_007.npy,0.278197
78,standardsnpy_MS2_682_9_683_0_000.npy,standardsnpy_MS1_287_0_287_1_007.npy,0.154812
79,standardsnpy_MS2_683_9_684_0_000.npy,standardsnpy_MS1_287_0_287_1_007.npy,0.141993
80,standardsnpy_MS2_684_9_685_0_000.npy,standardsnpy_MS1_287_0_287_1_007.npy,0.174479
81,standardsnpy_MS2_89_0_89_1_003.npy,standardsnpy_MS1_287_0_287_1_006.npy,0.162091

In [31]:
# === Getting info on RT of every single peak to be able to match them with MsDial ===
rt_range = [100,1100]
rt_bin_size = 0.73
rt_bins = np.arange(rt_range[0], rt_range[1]+rt_bin_size, rt_bin_size) 

sample_no = 1 # taking QC for the int for m/z (maybe chosen differently?)

rt_av = []

for i in range(len(image_name)):
    img = np.load(os.path.join(f'/home/frz603/DSP/matrix_standards/raw_images/clustering/labels_20/sn3_w6/single_labels_overlap/{image_name[i]}'))
    bin_range = [min(np.where(img>0)[1])+max(np.where(img>0)[1])]
    rt_av = np.append(rt_av, rt_bins[int(np.ceil(np.sum(bin_range)/2))])

rt_info = pd.DataFrame({'image_name': image_name, 'av_rt': rt_av})
rt_info

                             image_name    av_rt
0  standardsnpy_MS1_287_0_287_1_000.npy   342.36
1  standardsnpy_MS1_287_0_287_1_001.npy   561.36
2  standardsnpy_MS1_287_0_287_1_002.npy   684.00
3  standardsnpy_MS1_287_0_287_1_003.npy   765.03
4  standardsnpy_MS1_287_0_287_1_004.npy   827.08
5  standardsnpy_MS1_287_0_287_1_005.npy   857.74
6  standardsnpy_MS1_287_0_287_1_006.npy  1029.29
7  standardsnpy_MS1_287_0_287_1_007.npy  1054.84

In [34]:
ms2_image = []
int_spectra = []

for i in range(len(rt_info)):
    int_image = []
    ms2_chosen = spectra[spectra['ms1_name']==rt_info['image_name'].iloc[i]].reset_index(drop = True)
    for k in range(len(ms2_chosen)):
        img = np.load(f'/home/frz603/DSP/matrix_standards/raw_images/clustering/labels_20/sn3_w6/single_labels_overlap/{ms2_chosen.loc[k,'ms2_name']}')[sample_no]
        int_image.append(np.max(img))
    ms2_chosen = np.unique([int(f.split('_')[2]) for f in ms2_chosen['ms2_name']])
    ms2_image.append(ms2_chosen)
    int_spectra.append(int_image)

rt_info['mz'] = ms2_image
rt_info['int'] = int_spectra

rt_info

,image_name,av_rt,mz,int
0,standardsnpy_MS1_287_0_287_1_000.npy,342.36,[],[]
1,standardsnpy_MS1_287_0_287_1_001.npy,561.36,"[121, 123, 135, 149, 161, 245, 271, 272, 284, ...","[127.2631378173828, 125.72613525390624, 169.92..."
2,standardsnpy_MS1_287_0_287_1_002.npy,684.00,[287],[108.341796875]
3,standardsnpy_MS1_287_0_287_1_003.npy,765.03,[],[]
4,standardsnpy_MS1_287_0_287_1_004.npy,827.08,"[121, 213, 287, 288, 325, 331, 399]","[138.2740936279297, 115.26991271972656, 110.0,..."
5,standardsnpy_MS1_287_0_287_1_005.npy,857.74,"[153, 271]","[216.60421752929688, 101.76797485351562]"
6,standardsnpy_MS1_287_0_287_1_006.npy,1029.29,"[89, 135, 161, 213, 241, 259, 269, 287, 288, 2...","[332.87713623046875, 471.6954956054688, 403.52..."
7,standardsnpy_MS1_287_0_287_1_007.npy,1054.84,"[121, 127, 128, 137, 147, 157, 158, 160, 165, ...","[521.4660034179688, 414.7892456054688, 647.134..."

In [37]:
# === MS2 fragments from 2DLC ===
MS2_2d = pd.read_excel('/home/frz603/DSP/matrix_standards/2dlc.xlsx')
MS2_fragments = sorted(np.array([float(i.strip()) for i in MS2_2d.loc[MS2_2d['Name'] == stand_name, 'Fragments (m/z)'].iloc[0].split(',')]))

MS2_fragments

[np.float64(285.0391),
 np.float64(286.0427),
 np.float64(299.0186),
 np.float64(301.0357),
 np.float64(302.0392)]

In [39]:
stand_rt

array([ 769.62,  558.9 ,  682.8 ,  340.08,  822.54, 1025.88])

In [44]:
# === Choosing the most 'reliable' peak from MsDial and  ===
peak_ind = np.where(np.abs(np.diff(rt_info['av_rt'], stand_rt[stand['Fill %']==max(stand['Fill %'])][0])))

TypeError: 'numpy.float64' object cannot be interpreted as an integer

In [55]:

np.where(np.abs(stand_rt[stand['Fill %']==max(stand['Fill %'])][0]-rt_info['av_rt'])==np.max(np.abs(stand_rt[stand['Fill %']==max(stand['Fill %'])][0]-rt_info['av_rt'])))

(array([0]),)

In [52]:
rt_info['av_rt']

0     342.36
1     561.36
2     684.00
3     765.03
4     827.08
5     857.74
6    1029.29
7    1054.84
Name: av_rt, dtype: float64